version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: weather-forecast-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather
    ports:
      - 5432:5432